### ISSUE TITLE
In chapter 12, why do we no longer have Store.ts file in frontend part?

### ISSUE THREAD

**Issue by linhtch90** [PacktPublishing/ASP.NET-Core-5-and-React-Second-Edition#24]
ASP.NET-Core-5-and-React-Second-Edition/chapter-12/start/frontend/src/

Store.ts file, which related to state management using Redux, is introduced in Chapter 7. However, in Chapter 12, this file disappears? What is the reason behind this?

**Comment by carlrip** [comment]
Good question! 

Redux adds a bit of complexity to app which I thought would detract from subsequent chapters. Chapter 12 in particular is a big chapter that I didn’t want to complicate even more with Redux.

If we revise the book again, we’ll consider leaving the redux implementation in.

**Comment by linhtch90** [comment]
Thank you for your answer! The problem is clear now.
