### ISSUE TITLE
In chapter 7 Creating the store

### ISSUE THREAD

**Issue by waleedNasser** [PacktPublishing/ASP.NET-Core-5-and-React-Second-Edition#25]
in step 2 when use combineReducer function i have got an error and i don't know what's wrong please help this error message
 
No overload matches this call.
  Overload 1 of 3, '(reducers: ReducersMapObject<Appstate, any>): Reducer<CombinedState<Appstate>, AnyAction>', gave the following error.
    Type '(state: QuestionState | undefined, action: QuestionActions) => QuestionState | { unanswered: QuestionData[]; loading: boolean; unawnsered: QuestionData[]; viewing: QuestionData | null; searched: QuestionData[]; } | { ...; }' is not assignable to type 'Reducer<QuestionState, any>'.
      Type 'QuestionState | { unanswered: QuestionData[]; loading: boolean; unawnsered: QuestionData[]; viewing: QuestionData | null; searched: QuestionData[]; } | { ...; }' is not assignable to type 'QuestionState'.
        Type '{ viewing: QuestionData | undefined; loading: boolean; unawnsered: QuestionData[]; searched: QuestionData[]; }' is not assignable to type 'QuestionState'.
          Types of property 'viewing' are incompatible.
            Type 'QuestionData | undefined' is not assignable to type 'QuestionData | null'.
              Type 'undefined' is not assignable to type 'QuestionData | null'.
  Overload 2 of 3, '(reducers: ReducersMapObject<Appstate, AnyAction>): Reducer<CombinedState<Appstate>, AnyAction>', gave the following error.
    Type '(state: QuestionState | undefined, action: QuestionActions) => QuestionState | { unanswered: QuestionData[]; loading: boolean; unawnsered: QuestionData[]; viewing: QuestionData | null; searched: QuestionData[]; } | { ...; }' is not assignable to type 'Reducer<QuestionState, AnyAction>'.
      Type 'QuestionState | { unanswered: QuestionData[]; loading: boolean; unawnsered: QuestionData[]; viewing: QuestionData | null; searched: QuestionData[]; } | { ...; }' is not assignable to type 'QuestionState'.
        Type '{ viewing: QuestionData | undefined; loading: boolean; unawnsered: QuestionData[]; searched: QuestionData[]; }' is not assignable to type 'QuestionState'.  TS2769
I

**Comment by ErinNPeters** [comment]
How did you end up fixing this?
