### ISSUE TITLE
Chapter-03 finish react-scripts start issue

### ISSUE THREAD

**Issue by hmurty** [PacktPublishing/ASP.NET-Core-5-and-React-Second-Edition#3]
>npm install completes OK
> npm start leads to following message:
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.17.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle frontend@0.1.0~prestart: frontend@0.1.0
6 info lifecycle frontend@0.1.0~start: frontend@0.1.0
7 verbose lifecycle frontend@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle frontend@0.1.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Hal\Documents\Packt\ASP.NET-Core-5-and-React-Second-Edition-master fm GitHub\ASP.NET-Core-5-and-React-Second-Edition-master\chapter-03\finish\frontend\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python38\Scripts\;C:\Python38\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Brackets\command;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;;C:\Program Files\Azure Data Studio\bin;C:\Program Files (x86)\dotnet\;C:\Users\Hal\AppData\Local\Microsoft\WindowsApps;C:\Users\Hal\.dotnet\tools;C:\Users\Hal\AppData\Local\Programs\Azure Data Studio\bin;C:\Users\Hal\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Hal\AppData\Roaming\npm;C:\Program Files (x86)\DTN\IQFeed;C:\Users\Hal\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Azure Data Studio\bin;C:\Users\Hal\.dotnet\tools
9 verbose lifecycle frontend@0.1.0~start: CWD: C:\Users\Hal\Documents\Packt\ASP.NET-Core-5-and-React-Second-Edition-master fm GitHub\ASP.NET-Core-5-and-React-Second-Edition-master\chapter-03\finish\frontend
10 silly lifecycle frontend@0.1.0~start: Args: [ '/d /s /c', 'react-scripts start' ]
11 silly lifecycle frontend@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle frontend@0.1.0~start: Failed to exec start script
13 verbose stack Error: frontend@0.1.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid frontend@0.1.0
15 verbose cwd C:\Users\Hal\Documents\Packt\ASP.NET-Core-5-and-React-Second-Edition-master fm GitHub\ASP.NET-Core-5-and-React-Second-Edition-master\chapter-03\finish\frontend
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.17.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error frontend@0.1.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the frontend@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

from terminal:
PS C:\Users\Hal\Documents\Packt\ASP.NET-Core-5-and-React-Second-Edition-master fm GitHub\ASP.NET-Core-5-and-React-Second-Edition-master\chapter-03\finish\frontend> npm start

> frontend@0.1.0 start C:\Users\Hal\Documents\Packt\ASP.NET-Core-5-and-React-Second-Edition-master fm GitHub\ASP.NET-Core-5-and-React-Second-Edition-master\chapter-03\finish\frontend
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

lines from package.json:

  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },

lines from package-lock.json

    "react-scripts": {
      "version": "4.0.1",
      "resolved": "https://registry.npmjs.org/react-scripts/-/react-scripts-4.0.1.tgz",
      "integrity": "sha512-NnniMSC/wjwhcJAyPJCWtxx6CWONqgvGgV9+QXj1bwoW/JI++YF1eEf3Upf/mQ9KmP57IBdjzWs1XvnPq7qMTQ==",
      "requires": {
...

**Comment by carlrip** [comment]
It seems like something went wrong with that installation ...
Does npm_modules/react-scripts/bin/react-scripts.js exists?

I'd delete the npm_modules folder, do a `npm install` again, and try `npm start` again

**Comment by hmurty** [comment]
Thank you!It works now.hmurty
    On Thursday, February 25, 2021, 10:27:14 AM PST, Carl Rippon <notifications@github.com> wrote:  
 
 


It seems like something went wrong with that installation ...
Does npm_modules/react-scripts/bin/react-scripts.js exists?

I'd delete the npm_modules folder, do a npm install again, and try npm start again
