### ISSUE TITLE
Chapter 6 Page 193 code issue

### ISSUE THREAD

**Issue by elena-ar19** [PacktPublishing/ASP.NET-Core-5-and-React-Second-Edition#41]
I am getting the following error:

![image](https://user-images.githubusercontent.com/74960124/147513619-ba26a906-d9fb-4a03-81b4-a5ebeceaf82d.png)

![image](https://user-images.githubusercontent.com/74960124/147513740-8062c34b-7d8a-49f7-8a7f-3dc64e351369.png)

**Comment by carlrip** [comment]
The React Hook Form API has changed a little since this book was published. 
Have a look at this issue for how to resolve this: 
https://github.com/PacktPublishing/ASP.NET-Core-5-and-React-Second-Edition/issues/19#issuecomment-850799134

**Comment by elena-ar19** [comment]
Thanks a lot.
