### ISSUE TITLE
'"react-router-dom"' has no exported member named 'Routes'. (in chapter 5)

### ISSUE THREAD

**Issue by abase0001** [PacktPublishing/ASP.NET-Core-5-and-React-Second-Edition#6]
I followed the book in chapter 5 but got this error. The version of react-router-dom I have installed is 6.14.12. Could someone please help? Thank you.

![image](https://user-images.githubusercontent.com/53175738/114715517-ba6e9880-9d65-11eb-8557-3168dab5258a.png)

**Comment by carlrip** [comment]
Are you sure you have installed React Router 6? version 6 is still in beta ...
Try `npm install @react-router-dom@next`

**Comment by abase0001** [comment]
I don't know why I followed the insturctions to install react-router-dom but seemed that something is different. My visual studio core can recognize react route codes on this website ( https://reactrouter.com/web/example/basic ) but can't understand codes in the book.
Anyway, thanks a lot. I tried `npm install react-router-dom@next` (no @ before react-router-dom), and it works now. Thank you.
